title: Daniel Reeves - Blog
description: >-
  I write things.
url: "https://dwreeves.github.io/blog"
twitter_username: mueblesfeos
github_username:  dwreeves

remote_theme: samarsault/plainwhite-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

plainwhite:
  name: Daniel Reeves
  tagline: Data thingies
  date_format: "%b %-d, %Y"
  portfolio_image:  "assets/me.jpg"

  social_links:
    twitter: mueblesfeos
    github: dwreeves
    linkedIn: in/daniel-reeves-27700545 # format: locale/username

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
